"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RankTier = exports.SafetyLevel = exports.ContentSafetyLevel = exports.QuestionTopic = exports.QuestionCategory = exports.UserRole = exports.PowerUpType = exports.GameStatus = exports.Difficulty = exports.GameMode = void 0;
var GameMode;
(function (GameMode) {
    GameMode["Solo"] = "solo";
    GameMode["Teams"] = "teams";
    GameMode["Mixed"] = "mixed";
    GameMode["Survival"] = "survival";
    GameMode["Blitz"] = "blitz";
    GameMode["Conquest"] = "conquest";
    GameMode["Custom"] = "custom";
})(GameMode || (exports.GameMode = GameMode = {}));
var Difficulty;
(function (Difficulty) {
    Difficulty["Novice"] = "novice";
    Difficulty["Scholar"] = "scholar";
    Difficulty["Sage"] = "sage";
    Difficulty["Master"] = "master";
    Difficulty["Legend"] = "legend";
    Difficulty["Easy"] = "novice";
    Difficulty["Medium"] = "scholar";
    Difficulty["Hard"] = "sage";
    Difficulty["Genius"] = "master";
    Difficulty["Extreme"] = "legend";
})(Difficulty || (exports.Difficulty = Difficulty = {}));
var GameStatus;
(function (GameStatus) {
    GameStatus["Lobby"] = "lobby";
    GameStatus["PowerUpSelect"] = "powerup_select";
    GameStatus["Countdown"] = "countdown";
    GameStatus["Question"] = "question";
    GameStatus["AnswerReveal"] = "answer_reveal";
    GameStatus["Results"] = "results";
    GameStatus["Ended"] = "ended";
})(GameStatus || (exports.GameStatus = GameStatus = {}));
var PowerUpType;
(function (PowerUpType) {
    PowerUpType["Shield"] = "shield";
    PowerUpType["FiftyFifty"] = "fifty_fifty";
    PowerUpType["Freeze"] = "freeze";
    PowerUpType["DoubleDown"] = "double_down";
    PowerUpType["Steal"] = "steal";
    PowerUpType["DoublePick"] = "double_pick";
    PowerUpType["Whole"] = "whole";
    PowerUpType["Sandstorm"] = "sandstorm";
    PowerUpType["TimeWarp"] = "time_warp";
})(PowerUpType || (exports.PowerUpType = PowerUpType = {}));
var UserRole;
(function (UserRole) {
    UserRole["Guest"] = "guest";
    UserRole["Free"] = "free";
    UserRole["Subscriber"] = "subscriber";
    UserRole["Admin"] = "admin";
})(UserRole || (exports.UserRole = UserRole = {}));
var QuestionCategory;
(function (QuestionCategory) {
    QuestionCategory["Anime"] = "anime";
    QuestionCategory["Movies"] = "movies";
    QuestionCategory["TVSeries"] = "tv_series";
    QuestionCategory["Games"] = "games";
    QuestionCategory["Music"] = "music";
    QuestionCategory["InternetCulture"] = "internet_culture";
    QuestionCategory["Technology"] = "technology";
    QuestionCategory["Mathematics"] = "math";
    QuestionCategory["Logic"] = "logic";
    QuestionCategory["History"] = "history";
    QuestionCategory["Sports"] = "sports";
    QuestionCategory["General"] = "general";
    QuestionCategory["Science"] = "science";
    QuestionCategory["Language"] = "language";
    QuestionCategory["Islamic"] = "islamic";
    QuestionCategory["Comics"] = "comics";
    QuestionCategory["Streaming"] = "streaming";
    QuestionCategory["CurrentAffairs"] = "current_affairs";
    QuestionCategory["ANIME"] = "anime";
    QuestionCategory["MOVIES"] = "movies";
    QuestionCategory["TV_SERIES"] = "tv_series";
    QuestionCategory["GAMING"] = "games";
    QuestionCategory["MUSIC"] = "music";
    QuestionCategory["INTERNET_CULTURE"] = "internet_culture";
    QuestionCategory["TECHNOLOGY"] = "technology";
    QuestionCategory["MATH"] = "math";
    QuestionCategory["LOGIC"] = "logic";
    QuestionCategory["HISTORY"] = "history";
    QuestionCategory["SPORTS"] = "sports";
    QuestionCategory["GENERAL"] = "general";
    QuestionCategory["SCIENCE"] = "science";
    QuestionCategory["LANGUAGE"] = "language";
    QuestionCategory["ISLAMIC"] = "islamic";
    QuestionCategory["Math"] = "math";
})(QuestionCategory || (exports.QuestionCategory = QuestionCategory = {}));
var QuestionTopic;
(function (QuestionTopic) {
    QuestionTopic["Geography"] = "geography";
    QuestionTopic["Capitals"] = "capitals";
    QuestionTopic["Flags"] = "flags";
    QuestionTopic["Landmarks"] = "landmarks";
    QuestionTopic["Inventions"] = "inventions";
    QuestionTopic["Physics"] = "physics";
    QuestionTopic["Chemistry"] = "chemistry";
    QuestionTopic["Biology"] = "biology";
    QuestionTopic["Astronomy"] = "astronomy";
    QuestionTopic["WorldHistory"] = "world_history";
    QuestionTopic["AncientCivilizations"] = "ancient_civilizations";
    QuestionTopic["ModernHistory"] = "modern_history";
    QuestionTopic["Wars"] = "wars";
    QuestionTopic["Arithmetic"] = "arithmetic";
    QuestionTopic["Algebra"] = "algebra";
    QuestionTopic["Geometry"] = "geometry";
    QuestionTopic["LogicPuzzles"] = "logic_puzzles";
    QuestionTopic["EnglishGrammar"] = "english_grammar";
    QuestionTopic["ArabicGrammar"] = "arabic_grammar";
    QuestionTopic["Vocabulary"] = "vocabulary";
    QuestionTopic["Proverbs"] = "proverbs";
    QuestionTopic["Literature"] = "literature";
    QuestionTopic["Quran"] = "quran";
    QuestionTopic["Hadith"] = "hadith";
    QuestionTopic["Seerah"] = "seerah";
    QuestionTopic["Fiqh"] = "fiqh";
    QuestionTopic["Football"] = "football";
    QuestionTopic["Basketball"] = "basketball";
    QuestionTopic["Tennis"] = "tennis";
    QuestionTopic["Olympics"] = "olympics";
    QuestionTopic["AnimeSeries"] = "anime_series";
    QuestionTopic["Manga"] = "manga";
    QuestionTopic["AnimeCharacters"] = "anime_characters";
    QuestionTopic["AnimeBattles"] = "anime_battles";
    QuestionTopic["FilmPlots"] = "film_plots";
    QuestionTopic["FamousFilms"] = "famous_films";
    QuestionTopic["Actors"] = "actors";
    QuestionTopic["Scenes"] = "scenes";
    QuestionTopic["VideoGames"] = "video_games";
    QuestionTopic["GameMechanics"] = "game_mechanics";
    QuestionTopic["Esports"] = "esports";
    QuestionTopic["Programming"] = "programming";
    QuestionTopic["AI"] = "ai";
    QuestionTopic["Cybersecurity"] = "cybersecurity";
    QuestionTopic["InternetHistory"] = "internet_history";
})(QuestionTopic || (exports.QuestionTopic = QuestionTopic = {}));
var ContentSafetyLevel;
(function (ContentSafetyLevel) {
    ContentSafetyLevel["FullAI"] = "full_ai";
    ContentSafetyLevel["ControlledAI"] = "controlled_ai";
    ContentSafetyLevel["StrictVerified"] = "strict_verified";
})(ContentSafetyLevel || (exports.ContentSafetyLevel = ContentSafetyLevel = {}));
var SafetyLevel;
(function (SafetyLevel) {
    SafetyLevel["LEVEL_1_AI_SAFE"] = "level_1_ai_safe";
    SafetyLevel["LEVEL_2_CONTROLLED"] = "level_2_controlled";
    SafetyLevel["LEVEL_3_VERIFIED"] = "level_3_verified";
})(SafetyLevel || (exports.SafetyLevel = SafetyLevel = {}));
var RankTier;
(function (RankTier) {
    RankTier["Bronze"] = "bronze";
    RankTier["Silver"] = "silver";
    RankTier["Gold"] = "gold";
    RankTier["Platinum"] = "platinum";
    RankTier["Diamond"] = "diamond";
    RankTier["Grandmaster"] = "grandmaster";
})(RankTier || (exports.RankTier = RankTier = {}));
